/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypersIndexRouteImport } from './routes/typers/index'
import { Route as DefyIndexRouteImport } from './routes/defy/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypersIndexRoute = TypersIndexRouteImport.update({
  id: '/typers/',
  path: '/typers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DefyIndexRoute = DefyIndexRouteImport.update({
  id: '/defy/',
  path: '/defy/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/defy/': typeof DefyIndexRoute
  '/typers/': typeof TypersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/defy': typeof DefyIndexRoute
  '/typers': typeof TypersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/defy/': typeof DefyIndexRoute
  '/typers/': typeof TypersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/defy/' | '/typers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/defy' | '/typers'
  id: '__root__' | '/' | '/defy/' | '/typers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefyIndexRoute: typeof DefyIndexRoute
  TypersIndexRoute: typeof TypersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typers/': {
      id: '/typers/'
      path: '/typers'
      fullPath: '/typers/'
      preLoaderRoute: typeof TypersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defy/': {
      id: '/defy/'
      path: '/defy'
      fullPath: '/defy/'
      preLoaderRoute: typeof DefyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefyIndexRoute: DefyIndexRoute,
  TypersIndexRoute: TypersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
